[workspace]
members = [
    "chronicle_domain",
    "chronicle_memory",
    "chronicle_persistence",
    "chronicle_postgres",
    "examples/bank",
    "examples/counter",
    "examples/todo_list",
]
