[package]
name = "chronicle_persistence"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]

[dependencies]
futures = "0.1.10"
uuid = { version = "0.2", features = ["serde", "v4"] }
